import type { Db, DbClient } from "./db";
import { DEFAULT_MODULES } from "./modules";

async function addColumn(db: DbClient, table: string, definition: string) {
  try {
    await db.exec(`ALTER TABLE ${table} ADD COLUMN ${definition}`);
  } catch {
    // already present
  }
}

export async function migrateV2(db: Db, dialect: "sqlite" | "postgres") {
  const id =
    dialect === "postgres"
      ? "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
      : "INTEGER PRIMARY KEY AUTOINCREMENT";
  const now =
    dialect === "postgres"
      ? "TEXT NOT NULL DEFAULT to_char((now() AT TIME ZONE 'utc'), 'YYYY-MM-DD HH24:MI:SS')"
      : "TEXT NOT NULL DEFAULT (datetime('now'))";

  const statements = [
    `CREATE TABLE IF NOT EXISTS users (
      id ${id},
      email TEXT NOT NULL UNIQUE,
      name TEXT NOT NULL,
      password_hash TEXT NOT NULL,
      created_at ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS sessions (
      id ${id},
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      token TEXT NOT NULL UNIQUE,
      business_id INTEGER,
      expires_at TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS businesses (
      id ${id},
      name TEXT NOT NULL,
      currency TEXT NOT NULL DEFAULT 'USD',
      fiscal_year_start TEXT NOT NULL DEFAULT '01-01',
      lock_date TEXT,
      locale TEXT NOT NULL DEFAULT 'en-US',
      date_format TEXT NOT NULL DEFAULT 'yyyy-mm-dd',
      number_format TEXT NOT NULL DEFAULT '1,234.56',
      direction TEXT NOT NULL DEFAULT 'ltr',
      theme TEXT NOT NULL DEFAULT 'light',
      invoice_theme TEXT NOT NULL DEFAULT 'classic',
      footer_text TEXT NOT NULL DEFAULT '',
      smtp_json TEXT NOT NULL DEFAULT '{}',
      withholding_json TEXT NOT NULL DEFAULT '{}',
      modules_json TEXT NOT NULL,
      created_at ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS memberships (
      id ${id},
      user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      business_id INTEGER NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
      role TEXT NOT NULL,
      permissions_json TEXT NOT NULL DEFAULT '{}',
      UNIQUE (user_id, business_id)
    )`,
    `CREATE TABLE IF NOT EXISTS account_folders (
      id ${id},
      business_id INTEGER NOT NULL,
      name TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS divisions (
      id ${id},
      business_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      code TEXT NOT NULL DEFAULT ''
    )`,
    `CREATE TABLE IF NOT EXISTS tax_codes (
      id ${id},
      business_id INTEGER NOT NULL,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      rate_bps INTEGER NOT NULL DEFAULT 0,
      inclusive INTEGER NOT NULL DEFAULT 0,
      reverse_charge INTEGER NOT NULL DEFAULT 0,
      components_json TEXT NOT NULL DEFAULT '[]'
    )`,
    `CREATE TABLE IF NOT EXISTS currencies (
      id ${id},
      business_id INTEGER NOT NULL,
      code TEXT NOT NULL,
      name TEXT NOT NULL,
      rate_to_base INTEGER NOT NULL DEFAULT 10000
    )`,
    `CREATE TABLE IF NOT EXISTS custom_fields (
      id ${id},
      business_id INTEGER NOT NULL,
      entity TEXT NOT NULL,
      name TEXT NOT NULL,
      kind TEXT NOT NULL,
      options_json TEXT NOT NULL DEFAULT '[]',
      placement TEXT NOT NULL DEFAULT 'header',
      sort_order INTEGER NOT NULL DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS custom_field_values (
      id ${id},
      field_id INTEGER NOT NULL REFERENCES custom_fields(id) ON DELETE CASCADE,
      entity_id INTEGER NOT NULL,
      value TEXT NOT NULL DEFAULT ''
    )`,
    `CREATE TABLE IF NOT EXISTS parties (
      id ${id},
      business_id INTEGER NOT NULL,
      kind TEXT NOT NULL,
      name TEXT NOT NULL,
      email TEXT NOT NULL DEFAULT '',
      address TEXT NOT NULL DEFAULT '',
      credit_limit_cents INTEGER NOT NULL DEFAULT 0,
      control_account_id INTEGER,
      currency TEXT NOT NULL DEFAULT ''
    )`,
    `CREATE TABLE IF NOT EXISTS documents (
      id ${id},
      business_id INTEGER NOT NULL,
      kind TEXT NOT NULL,
      number TEXT NOT NULL,
      party_id INTEGER,
      date TEXT NOT NULL,
      due_date TEXT,
      status TEXT NOT NULL DEFAULT 'draft',
      currency TEXT NOT NULL DEFAULT 'USD',
      notes TEXT NOT NULL DEFAULT '',
      reference TEXT NOT NULL DEFAULT '',
      project_id INTEGER,
      division_id INTEGER,
      journal_entry_id INTEGER,
      source_id INTEGER,
      recurring_id INTEGER,
      discount_bps INTEGER NOT NULL DEFAULT 0,
      tax_cents INTEGER NOT NULL DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS document_lines (
      id ${id},
      document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
      description TEXT NOT NULL,
      qty DOUBLE PRECISION NOT NULL DEFAULT 1,
      unit_cents INTEGER NOT NULL DEFAULT 0,
      account_id INTEGER,
      tax_code_id INTEGER,
      item_id INTEGER,
      project_id INTEGER,
      discount_bps INTEGER NOT NULL DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS document_payments (
      id ${id},
      document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,
      cash_account_id INTEGER,
      date TEXT NOT NULL,
      amount_cents INTEGER NOT NULL,
      journal_entry_id INTEGER
    )`,
    `CREATE TABLE IF NOT EXISTS bank_moves (
      id ${id},
      business_id INTEGER NOT NULL,
      kind TEXT NOT NULL,
      cash_account_id INTEGER NOT NULL,
      offset_account_id INTEGER,
      dest_cash_account_id INTEGER,
      date TEXT NOT NULL,
      amount_cents INTEGER NOT NULL,
      memo TEXT NOT NULL DEFAULT '',
      reference TEXT NOT NULL DEFAULT '',
      project_id INTEGER,
      division_id INTEGER,
      journal_entry_id INTEGER,
      party_id INTEGER
    )`,
    `CREATE TABLE IF NOT EXISTS bank_statement_lines (
      id ${id},
      business_id INTEGER NOT NULL,
      cash_account_id INTEGER NOT NULL,
      date TEXT NOT NULL,
      amount_cents INTEGER NOT NULL,
      description TEXT NOT NULL DEFAULT '',
      matched_move_id INTEGER
    )`,
    `CREATE TABLE IF NOT EXISTS bank_rules (
      id ${id},
      business_id INTEGER NOT NULL,
      pattern TEXT NOT NULL,
      account_id INTEGER NOT NULL,
      kind TEXT NOT NULL DEFAULT 'contains'
    )`,
    `CREATE TABLE IF NOT EXISTS expense_claims (
      id ${id},
      business_id INTEGER NOT NULL,
      payer_name TEXT NOT NULL,
      date TEXT NOT NULL,
      amount_cents INTEGER NOT NULL,
      account_id INTEGER,
      memo TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'open',
      journal_entry_id INTEGER
    )`,
    `CREATE TABLE IF NOT EXISTS time_entries (
      id ${id},
      business_id INTEGER NOT NULL,
      party_id INTEGER,
      project_id INTEGER,
      date TEXT NOT NULL,
      hours DOUBLE PRECISION NOT NULL,
      rate_cents INTEGER NOT NULL DEFAULT 0,
      memo TEXT NOT NULL DEFAULT '',
      invoiced INTEGER NOT NULL DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS billable_expenses (
      id ${id},
      business_id INTEGER NOT NULL,
      party_id INTEGER,
      project_id INTEGER,
      date TEXT NOT NULL,
      amount_cents INTEGER NOT NULL,
      memo TEXT NOT NULL DEFAULT '',
      invoiced INTEGER NOT NULL DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS projects (
      id ${id},
      business_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      code TEXT NOT NULL DEFAULT '',
      status TEXT NOT NULL DEFAULT 'active'
    )`,
    `CREATE TABLE IF NOT EXISTS items (
      id ${id},
      business_id INTEGER NOT NULL,
      sku TEXT NOT NULL DEFAULT '',
      name TEXT NOT NULL,
      kind TEXT NOT NULL DEFAULT 'inventory',
      costing TEXT NOT NULL DEFAULT 'average',
      unit_cost_cents INTEGER NOT NULL DEFAULT 0,
      income_account_id INTEGER,
      expense_account_id INTEGER,
      inventory_account_id INTEGER
    )`,
    `CREATE TABLE IF NOT EXISTS item_components (
      id ${id},
      kit_id INTEGER NOT NULL,
      item_id INTEGER NOT NULL,
      qty DOUBLE PRECISION NOT NULL DEFAULT 1
    )`,
    `CREATE TABLE IF NOT EXISTS locations (
      id ${id},
      business_id INTEGER NOT NULL,
      name TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS stock_moves (
      id ${id},
      business_id INTEGER NOT NULL,
      item_id INTEGER NOT NULL,
      location_id INTEGER,
      qty DOUBLE PRECISION NOT NULL,
      unit_cost_cents INTEGER NOT NULL DEFAULT 0,
      kind TEXT NOT NULL,
      date TEXT NOT NULL,
      memo TEXT NOT NULL DEFAULT ''
    )`,
    `CREATE TABLE IF NOT EXISTS employees (
      id ${id},
      business_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      email TEXT NOT NULL DEFAULT '',
      role_title TEXT NOT NULL DEFAULT '',
      pay_cents INTEGER NOT NULL DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS payslips (
      id ${id},
      business_id INTEGER NOT NULL,
      employee_id INTEGER NOT NULL,
      date TEXT NOT NULL,
      memo TEXT NOT NULL DEFAULT '',
      journal_entry_id INTEGER,
      status TEXT NOT NULL DEFAULT 'draft'
    )`,
    `CREATE TABLE IF NOT EXISTS payslip_items (
      id ${id},
      payslip_id INTEGER NOT NULL REFERENCES payslips(id) ON DELETE CASCADE,
      name TEXT NOT NULL,
      kind TEXT NOT NULL,
      amount_cents INTEGER NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS assets (
      id ${id},
      business_id INTEGER NOT NULL,
      kind TEXT NOT NULL,
      name TEXT NOT NULL,
      cost_cents INTEGER NOT NULL,
      residual_cents INTEGER NOT NULL DEFAULT 0,
      life_months INTEGER NOT NULL DEFAULT 60,
      start_date TEXT NOT NULL,
      account_id INTEGER,
      expense_account_id INTEGER,
      accumulated_cents INTEGER NOT NULL DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS investments (
      id ${id},
      business_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
      cost_cents INTEGER NOT NULL DEFAULT 0,
      market_cents INTEGER NOT NULL DEFAULT 0,
      account_id INTEGER
    )`,
    `CREATE TABLE IF NOT EXISTS capital_accounts (
      id ${id},
      business_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      account_id INTEGER NOT NULL,
      parent_id INTEGER,
      special INTEGER NOT NULL DEFAULT 0
    )`,
    `CREATE TABLE IF NOT EXISTS saved_reports (
      id ${id},
      business_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      config_json TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS access_tokens (
      id ${id},
      business_id INTEGER NOT NULL,
      name TEXT NOT NULL,
      token_hash TEXT NOT NULL,
      created_at ${now}
    )`,
    `CREATE TABLE IF NOT EXISTS recurring (
      id ${id},
      business_id INTEGER NOT NULL,
      kind TEXT NOT NULL,
      next_date TEXT NOT NULL,
      interval_days INTEGER NOT NULL DEFAULT 30,
      template_json TEXT NOT NULL,
      active INTEGER NOT NULL DEFAULT 1
    )`,
    `CREATE TABLE IF NOT EXISTS form_defaults (
      id ${id},
      business_id INTEGER NOT NULL,
      entity TEXT NOT NULL UNIQUE,
      defaults_json TEXT NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS idx_documents_biz ON documents(business_id, kind, date)`,
    `CREATE INDEX IF NOT EXISTS idx_parties_biz ON parties(business_id, kind)`,
    `CREATE INDEX IF NOT EXISTS idx_bank_moves_biz ON bank_moves(business_id, date)`,
  ];

  for (const statement of statements) {
    await db.exec(statement);
  }

  await addColumn(db, "accounts", "business_id INTEGER");
  await addColumn(db, "accounts", "folder_id INTEGER");
  await addColumn(db, "accounts", "control_kind TEXT");
  await addColumn(db, "cash_accounts", "business_id INTEGER");
  await addColumn(db, "cash_accounts", "currency TEXT DEFAULT 'USD'");
  await addColumn(db, "journal_entries", "business_id INTEGER");
  await addColumn(db, "journal_entries", "division_id INTEGER");
  await addColumn(db, "journal_entries", "project_id INTEGER");
  await addColumn(db, "journal_entries", "reference TEXT DEFAULT ''");
  await addColumn(db, "journal_lines", "division_id INTEGER");
  await addColumn(db, "journal_lines", "project_id INTEGER");
  await addColumn(db, "customers", "business_id INTEGER");
  await addColumn(db, "invoices", "business_id INTEGER");
  await addColumn(db, "documents", "total INTEGER NOT NULL DEFAULT 0");

  await db.exec("UPDATE accounts SET business_id = 1 WHERE business_id IS NULL");
  await db.exec("UPDATE cash_accounts SET business_id = 1 WHERE business_id IS NULL");
  await db.exec("UPDATE journal_entries SET business_id = 1 WHERE business_id IS NULL");
  await db.exec("UPDATE customers SET business_id = 1 WHERE business_id IS NULL");
  await db.exec("UPDATE invoices SET business_id = 1 WHERE business_id IS NULL");

  const businesses = await db.get<{ n: number }>("SELECT COUNT(*) AS n FROM businesses");
  const legacy = await db.get<{ n: number }>("SELECT COUNT(*) AS n FROM business");
  if ((businesses?.n ?? 0) === 0 && (legacy?.n ?? 0) > 0) {
    const row = await db.get<{
      name: string;
      currency: string;
      fiscal_year_start: string;
      modules_json: string;
    }>("SELECT name, currency, fiscal_year_start, modules_json FROM business WHERE id = 1");
    if (row) {
      await db.run(
        "INSERT INTO businesses (id, name, currency, fiscal_year_start, modules_json) VALUES (?, ?, ?, ?, ?)",
        1,
        row.name,
        row.currency,
        row.fiscal_year_start,
        JSON.stringify({ ...DEFAULT_MODULES, ...(safeJson(row.modules_json) as object) }),
      );
    }
  }
}

function safeJson(raw: string): unknown {
  try {
    return JSON.parse(raw);
  } catch {
    return {};
  }
}
